### ISSUE TITLE
Disable rootFS verification failed

### ISSUE THREAD

**Issue by liujixings** [supechicken/ChromeOS-ARCVM-Root#1]
```
Disable rootFS verification now? (This will reboot your system) [Y/n]: y

job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Illegal seek

  ERROR: YOU ARE TRYING TO MODIFY THE LIVE SYSTEM IMAGE /dev/nvme0n1.

  The system may become unusable after that change, especially when you have
  some auto updates in progress. To make it safer, we suggest you to only
  change the partition you have booted with. To do that, re-execute this command
  as:

    sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 2

  If you are sure to modify other partition, please invoke the command again and
  explicitly assign only one target partition for each time  (--partitions N )
  
make_dev_ssd.sh: ERROR: IMAGE /dev/nvme0n1 IS NOT MODIFIED.
```

**Comment by supechicken** [comment]
Try this and run the installation script again after reboot:
```shell
sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 3
sudo /usr/share/vboot/bin/make_dev_ssd.sh --remove_rootfs_verification --partitions 5
sudo reboot
```

**Comment by djfaizp** [comment]
can you please compile kernel from below source as your kernel is not passing lots of permission and when i switch to default kernel everything works normally 
issue : network issue not internet connection to some android apps, but playstore works fine

https://chromium.googlesource.com/chromiumos/third_party/kernel/+/refs/heads/chromeos-5.10-arcvm

**Comment by supechicken** [comment]
> can you please compile kernel from below source as your kernel is not passing lots of permission and when i switch to default kernel everything works normally issue : network issue not internet connection to some android apps, but playstore works fine
> 
> https://chromium.googlesource.com/chromiumos/third_party/kernel/+/refs/heads/chromeos-5.10-arcvm

I have no idea about this. All kernel builds using the same `defconfig` would be identical, so I don't think rebuilding the kernel helps.

**Comment by djfaizp** [comment]
Can you please confirm clash of clans, golf rival,million lords this are few games i observe
