### ISSUE TITLE
can you please add Arm-NativeBridge to chrome os

### ISSUE THREAD

**Issue by djfaizp** [supechicken/ChromeOS-ARCVM-Root#2]
[Android x86 Arm NativeBridge (libhoudini)](https://github.com/SGNight/Arm-NativeBridge)

**Comment by supechicken** [comment]
This is beyond the scope of this project. However, I can try it and post it to another repo if success.

**Comment by djfaizp** [comment]
I will try using darkmatter os native bridge if this issue is due to that and another thing i used wsa on my pc its awsome apps are like pc performence
