### ISSUE TITLE
Android container will not load after rooting 

### ISSUE THREAD

**Issue by linusrg1** [supechicken/ChromeOS-ARCVM-Root#3]
Initially I wasn't able to disable rootfs verification. I got around this by rerunning the command and targeting the partition (partition 4) that the chromeos shell recommended I use. After running your script again though and rebooting, the android container simply wouldn't load, I couldn't run any apps. Any way I could fix this?

I have a lenovo chromebook duet by the way.

**Comment by supechicken** [comment]
Maybe try running the unroot script? It should revert all changes made by my script.

**Comment by supechicken** [comment]
Closing as no response.

**Comment by BaIanced** [comment]
Unrooting does solve the issue. I ran into the exact same problem as OP on a Lenovo Duet 5. 

Script and manual method didn't work. Android apps are just infinitely stuck trying to open :(
