### ISSUE TITLE
sudo: The "no new privileges" flag is set, which prevents sudo from running as root. sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.

### ISSUE THREAD

**Issue by asahiba** [supechicken/ChromeOS-ARCVM-Root#5]

**Comment by supechicken** [comment]
Due to the improved security features introduced in ChromeOS v117, the installation command needs to be run in the VT-2 shell now (by pressing `Ctrl + Alt + ->` and login with user `chronos`)

See chromebrew/chromebrew#8779 for more info.

**Comment by asahiba** [comment]
I entered the installation command but nothing happened

**Comment by asahiba** [comment]
My device is arm architecture

**Comment by asahiba** [comment]
![photo_2023-10-22_22-07-02](https://github.com/supechicken/ChromeOS-ARCVM-Root/assets/73240349/ce0532cb-242b-4b1c-89c9-4a2be4aa2653)
I think it's because I made a typo, but a new error appeared.
